"""
Daily Recommender Web Backend
FastAPI + WebSocket 实时日志
"""

import asyncio
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel

# 项目根目录
PROJECT_ROOT = Path(__file__).parent.absolute()
HISTORY_DIR = PROJECT_ROOT / "history"
CONFIG_FILE = PROJECT_ROOT / ".web_config.json"

app = FastAPI(title="Daily Recommender API", version="1.0.0")

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============== Models ==============

class Config(BaseModel):
    provider: str = "openai"
    model: str = "gpt-4o-mini"
    base_url: str = ""
    api_key: str = ""
    temperature: float = 0.5
    smtp_server: str = ""
    smtp_port: int = 465
    sender: str = ""
    receiver: str = ""
    smtp_password: str = ""
    gh_languages: str = "all"
    gh_since: str = "daily"
    gh_max_repos: int = 30
    hf_content_types: list = ["papers", "models"]
    hf_max_papers: int = 30
    hf_max_models: int = 15
    description: str = ""
    researcher_profile: str = ""


class RunRequest(BaseModel):
    sources: list[str]  # github, huggingface, twitter
    generate_report: bool = False
    generate_ideas: bool = False
    save: bool = True


# ============== Config API ==============

@app.get("/api/config")
def get_config():
    """获取当前配置"""
    if CONFIG_FILE.exists():
        content = CONFIG_FILE.read_text(encoding="utf-8")
        if content.strip():
            return json.loads(content)
    # 返回默认配置
    return {
        "provider": "openai",
        "model": "gpt-4o-mini",
        "base_url": "",
        "api_key": "",
        "temperature": 0.5,
        "smtp_server": "",
        "smtp_port": 465,
        "sender": "",
        "receiver": "",
        "smtp_password": "",
        "gh_languages": "all",
        "gh_since": "daily",
        "gh_max_repos": 30,
        "hf_content_types": ["papers", "models"],
        "hf_max_papers": 30,
        "hf_max_models": 15,
        "description": "",
        "researcher_profile": ""
    }


@app.post("/api/config")
def save_config(config: Config):
    """保存配置"""
    try:
        # 确保目录存在
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)

        # 使用 model_dump (Pydantic v2) 或 dict (Pydantic v1)
        config_dict = config.model_dump() if hasattr(config, 'model_dump') else config.dict()

        CONFIG_FILE.write_text(
            json.dumps(config_dict, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )

        # 同时写入 .env 文件供 main.py 使用
        env_content = f"""# Auto-generated by web UI
PROVIDER={config.provider}
MODEL_NAME={config.model}
BASE_URL={config.base_url}
API_KEY={config.api_key}
TEMPERATURE={config.temperature}
SMTP_SERVER={config.smtp_server}
SMTP_PORT={config.smtp_port}
SMTP_SENDER={config.sender}
SMTP_RECEIVER={config.receiver}
SMTP_PASSWORD={config.smtp_password}
GH_LANGUAGES={config.gh_languages}
GH_SINCE={config.gh_since}
GH_MAX_REPOS={config.gh_max_repos}
HF_CONTENT_TYPES={" ".join(config.hf_content_types)}
HF_MAX_PAPERS={config.hf_max_papers}
HF_MAX_MODELS={config.hf_max_models}
DESCRIPTION_FILE=profiles/description.txt
"""
        (PROJECT_ROOT / ".env").write_text(env_content, encoding="utf-8")

        # 写入 description.txt
        if config.description:
            (PROJECT_ROOT / "profiles").mkdir(parents=True, exist_ok=True)
            (PROJECT_ROOT / "profiles" / "description.txt").write_text(
                config.description, encoding="utf-8"
            )

        # 写入 researcher_profile.md
        if config.researcher_profile:
            (PROJECT_ROOT / "profiles").mkdir(parents=True, exist_ok=True)
            (PROJECT_ROOT / "profiles" / "researcher_profile.md").write_text(
                config.researcher_profile, encoding="utf-8"
            )

        return {"status": "ok"}
    except Exception as e:
        import traceback
        print(f"保存配置失败: {e}")
        print(traceback.format_exc())
        return JSONResponse({"status": "error", "message": str(e)}, status_code=500)


# ============== Run API ==============

async def run_daily_recommender(
    sources: list[str],
    generate_report: bool = False,
    generate_ideas: bool = False,
    save: bool = True
):
    """异步运行 daily-recommender"""

    today = datetime.now().strftime("%Y-%m-%d")
    result_dirs = []

    # 获取配置
    config = get_config()

    cmd = [
        sys.executable,
        "main.py",
        "--sources", *sources,
        "--num_workers", "4",
        "--provider", config.get("provider", "openai"),
        "--model", config.get("model", "gpt-4o-mini"),
        "--base_url", config.get("base_url", ""),
        "--api_key", config.get("api_key", ""),
        "--temperature", str(config.get("temperature", 0.5)),
    ]

    if save:
        cmd.append("--save")
    if generate_report:
        cmd.append("--generate_report")
        result_dirs.append(HISTORY_DIR / "reports" / today)
    if generate_ideas:
        cmd.append("--generate_ideas")
        cmd.extend(["--researcher_profile", "profiles/researcher_profile.md"])
        result_dirs.append(HISTORY_DIR / "ideas" / today)

    # GitHub 参数
    cmd.extend([
        "--gh_languages", config.get("gh_languages", "all"),
        "--gh_since", config.get("gh_since", "daily"),
        "--gh_max_repos", str(config.get("gh_max_repos", 30)),
    ])

    # HuggingFace 参数
    cmd.extend([
        "--hf_content_type", *config.get("hf_content_types", ["papers", "models"]),
        "--hf_max_papers", str(config.get("hf_max_papers", 30)),
        "--hf_max_models", str(config.get("hf_max_models", 15)),
    ])

    process = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
        cwd=str(PROJECT_ROOT)
    )

    while True:
        line = await process.stdout.readline()
        if not line:
            break
        text = line.decode("utf-8", errors="replace").rstrip()
        yield {"type": "log", "message": text}

    await process.wait()

    # 收集生成的文件
    generated_files = []
    for src in sources:
        result_dirs.append(HISTORY_DIR / src / today)

    for dir_path in result_dirs:
        if dir_path.exists():
            # 读取 Markdown 文件
            for md_file in dir_path.glob("*.md"):
                content = md_file.read_text(encoding="utf-8")
                generated_files.append({
                    "type": "markdown",
                    "name": md_file.name,
                    "content": content,
                    "source": dir_path.parent.name
                })
            # 读取 JSON 文件
            json_dir = dir_path / "json"
            if json_dir.exists():
                items = []
                for json_file in json_dir.glob("*.json"):
                    data = json.loads(json_file.read_text(encoding="utf-8"))
                    items.append(data)
                if items:
                    generated_files.append({
                        "type": "json_list",
                        "name": f"{dir_path.parent.name}_items",
                        "items": items,
                        "source": dir_path.parent.name
                    })

    yield {
        "type": "complete",
        "exit_code": process.returncode,
        "success": process.returncode == 0,
        "files": generated_files,
        "date": today
    }


@app.websocket("/ws/run")
async def websocket_run(websocket: WebSocket):
    """WebSocket 实时运行日志"""
    await websocket.accept()

    try:
        # 接收运行参数
        data = await websocket.receive_json()
        req = RunRequest(**data)

        await websocket.send_json({"type": "start", "message": "开始运行..."})

        async for msg in run_daily_recommender(
            sources=req.sources,
            generate_report=req.generate_report,
            generate_ideas=req.generate_ideas,
            save=req.save
        ):
            await websocket.send_json(msg)

    except WebSocketDisconnect:
        print("Client disconnected")
    except Exception as e:
        await websocket.send_json({
            "type": "error",
            "message": str(e)
        })


# ============== History API ==============

@app.get("/api/history")
def get_history():
    """获取历史运行记录"""
    history = []

    if not HISTORY_DIR.exists():
        return []

    for source_dir in HISTORY_DIR.iterdir():
        if not source_dir.is_dir():
            continue

        source_name = source_dir.name

        for date_dir in source_dir.iterdir():
            if not date_dir.is_dir():
                continue

            date_str = date_dir.name

            # 检查是否有结果文件
            has_results = list(date_dir.glob("*.md")) or list(date_dir.glob("*.html"))
            json_files = list(date_dir.glob("json/*.json"))

            if has_results or json_files:
                history.append({
                    "id": f"{source_name}_{date_str}",
                    "type": source_name,
                    "date": date_str,
                    "sources": [source_name.replace("_", ", ")],
                    "items": len(json_files),
                    "path": str(date_dir.relative_to(PROJECT_ROOT))
                })

    # 按日期倒序
    history.sort(key=lambda x: x["date"], reverse=True)
    return history


@app.get("/api/results/{source}/{date}")
def get_results(source: str, date: str):
    """获取某天的详细结果"""
    result_dir = HISTORY_DIR / source / date

    if not result_dir.exists():
        return JSONResponse({"error": "Not found"}, status_code=404)

    results = {
        "source": source,
        "date": date,
        "markdown_files": [],
        "html_files": [],
        "json_files": []
    }

    for f in result_dir.glob("*.md"):
        results["markdown_files"].append({
            "name": f.name,
            "content": f.read_text(encoding="utf-8")
        })

    for f in result_dir.glob("*.html"):
        results["html_files"].append({
            "name": f.name,
            "url": f"/api/file/{source}/{date}/{f.name}"
        })

    json_dir = result_dir / "json"
    if json_dir.exists():
        for f in json_dir.glob("*.json"):
            results["json_files"].append({
                "name": f.name,
                "data": json.loads(f.read_text(encoding="utf-8"))
            })

    return results


@app.get("/api/file/{source}/{date}/{filename}")
def get_file(source: str, date: str, filename: str):
    """获取文件内容"""
    file_path = HISTORY_DIR / source / date / filename

    if not file_path.exists():
        return JSONResponse({"error": "Not found"}, status_code=404)

    return FileResponse(file_path)


# ============== Static Files ==============

@app.get("/health")
def health_check():
    return {"status": "ok", "service": "Daily Recommender"}


@app.get("/")
def root():
    """返回前端页面"""
    return FileResponse(PROJECT_ROOT / "web-ui.html")


@app.get("/web-ui.html")
def web_ui():
    return FileResponse(PROJECT_ROOT / "web-ui.html")


# ============== Main ==============

if __name__ == "__main__":
    import uvicorn

    print(f"""
╔════════════════════════════════════════════════════════╗
║          Daily Recommender Web Server                  ║
╠════════════════════════════════════════════════════════╣
║  API Docs: http://localhost:8080/docs                  ║
║  Web UI:   http://localhost:8080/                      ║
╚════════════════════════════════════════════════════════╝
    """)

    uvicorn.run(app, host="0.0.0.0", port=8080)
